BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "hft"
BBFILE_PATTERN_hft = "^${LAYERDIR}/"
BBFILE_PRIORITY_hft = "20"

LAYERSERIES_COMPAT_hft = "scarthgap"
LAYERDEPENDS_hft = "core xilinx-core xilinx-bsp amd-adaptive-socs-bsp openembedded-layer rust-bin swupdate"
