[package]
name = "hft-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
hft-analytics = { path = "../analytics", version = "0.1.0" }
hft-protocol = { path = "../protocol", version = "0.1.0" }
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
mockall.workspace = true
tokio.workspace = true

[lints]
workspace = true
