[package]
name = "hftd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
hft-analytics = { path = "../analytics", version = "0.1.0" }
hft-ouch = { path = "../ouch", version = "0.1.0" }
hft-protocol = { path = "../protocol", version = "0.1.0" }
hft-rpmsg = { path = "../rpmsg", version = "0.1.0" }
hft-storage = { path = "../storage", version = "0.1.0" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-journald.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
mockall.workspace = true

[lints]
workspace = true
