"""Generate cross-language protocol constants and deterministic test vectors."""

from __future__ import annotations

import argparse
import hashlib
import json
import struct
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
SCHEMA_DIR = ROOT / "protocol" / "schema"


def load(name: str) -> dict[str, Any]:
    return json.loads((SCHEMA_DIR / name).read_text(encoding="utf-8"))


def schema_digest() -> str:
    digest = hashlib.sha256()
    for path in sorted(SCHEMA_DIR.glob("*.yaml")):
        digest.update(path.name.encode())
        digest.update(path.read_bytes())
    return digest.hexdigest()


def rust_hex(value: str) -> str:
    digits = value.removeprefix("0x")
    groups: list[str] = []
    while digits:
        groups.append(digits[-4:])
        digits = digits[:-4]
    return "0x" + "_".join(reversed(groups))


def cpp_header(itch: dict[str, Any], registers: dict[str, Any], digest: str) -> str:
    message_lines = "\n".join(
        f"  {message['name']} = '{message['type']}'," for message in itch["messages"]
    )
    length_lines = "\n".join(
        f"inline constexpr std::size_t {message['name']}_length = {message['length']};"
        for message in itch["messages"]
    )
    register_lines = "\n".join(
        f"inline constexpr std::uintptr_t {register['name'].lower()} = "
        f"{register['offset']}U;"
        for register in registers["registers"]
    )
    return f"""// Generated by protocol/generator/generate.py. Do not edit.
#pragma once

#include <array>
#include <bit>
#include <cstddef>
#include <cstdint>
#include <span>

namespace hft::protocol {{
inline constexpr std::uint16_t abi_version = 1;
inline constexpr std::size_t moldudp64_header_size = 20;
inline constexpr std::size_t ipc_record_size = 64;
inline constexpr char schema_sha256[] = "{digest}";

enum class itch_type : std::uint8_t {{
{message_lines}
}};

{length_lines}

[[nodiscard]] constexpr auto read_be_u16(std::span<std::byte const, 2> bytes)
    -> std::uint16_t {{
  return (std::to_integer<std::uint16_t>(bytes[0]) << 8U) |
         std::to_integer<std::uint16_t>(bytes[1]);
}}

[[nodiscard]] constexpr auto read_be_u32(std::span<std::byte const, 4> bytes)
    -> std::uint32_t {{
  std::uint32_t value{{}};
  for (auto byte : bytes) {{
    value = (value << 8U) | std::to_integer<std::uint32_t>(byte);
  }}
  return value;
}}

[[nodiscard]] constexpr auto read_be_u64(std::span<std::byte const, 8> bytes)
    -> std::uint64_t {{
  std::uint64_t value{{}};
  for (auto byte : bytes) {{
    value = (value << 8U) | std::to_integer<std::uint64_t>(byte);
  }}
  return value;
}}

namespace reg {{
inline constexpr std::uintptr_t base = {registers["base_address"]}U;
{register_lines}
}}  // namespace reg
}}  // namespace hft::protocol
"""


def rust_module(itch: dict[str, Any], registers: dict[str, Any], digest: str) -> str:
    variants = "\n".join(
        f"    {''.join(part.title() for part in message['name'].split('_'))} = b'{message['type']}',"
        for message in itch["messages"]
    )
    register_lines = "\n".join(
        f"    pub const {register['name']}: usize = {register['offset']};"
        for register in registers["registers"]
    )
    return f"""// Generated by protocol/generator/generate.py. Do not edit.
pub const ABI_VERSION: u16 = 1;
pub const MOLDUDP64_HEADER_SIZE: usize = 20;
pub const IPC_RECORD_SIZE: usize = 64;
pub const SCHEMA_SHA256: &str = "{digest}";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(u8)]
pub enum ItchType {{
{variants}
}}

pub mod reg {{
    pub const BASE: usize = {rust_hex(registers["base_address"])};
{register_lines}
}}
"""


def vhdl_package(itch: dict[str, Any], registers: dict[str, Any], digest: str) -> str:
    type_lines = "\n".join(
        f"  constant ITCH_{message['name'].upper()} : std_logic_vector(7 downto 0) "
        f':= x"{ord(message["type"]):02X}";'
        for message in itch["messages"]
    )
    register_lines = "\n".join(
        f"  constant REG_{register['name']} : natural := {int(register['offset'], 16)};"
        for register in registers["registers"]
    )
    return f"""-- Generated by protocol/generator/generate.py. Do not edit.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package hft_protocol_pkg is
  constant ABI_VERSION : natural := 1;
  constant MOLDUDP64_HEADER_SIZE : natural := 20;
  constant IPC_RECORD_SIZE : natural := 64;
  constant SCHEMA_SHA256 : string := "{digest}";
{type_lines}
{register_lines}
end package;
"""


def register_markdown(registers: dict[str, Any], digest: str) -> str:
    rows = [
        "| Name | Offset | Access | Reset | Description |",
        "| --- | ---: | :---: | ---: | --- |",
    ]
    for register in registers["registers"]:
        rows.append(
            f"| `{register['name']}` | `{register['offset']}` | "
            f"{register['access']} | `{register['reset']}` | "
            f"{register.get('description', '')} |"
        )
    return (
        "# Generated PL register map\n\n"
        f"Schema SHA-256: `{digest}`\n\n"
        f"Base address: `{registers['base_address']}`; span: `{registers['span']}`.\n\n"
        + "\n".join(rows)
        + "\n"
    )


def itch_add_message() -> bytes:
    timestamp = 123_456
    return b"".join(
        (
            b"A",
            struct.pack(">HH", 1, 2),
            timestamp.to_bytes(6, "big"),
            struct.pack(">Q", 0x0102_0304_0506_0708),
            b"B",
            struct.pack(">I", 100),
            b"ACME    ",
            struct.pack(">I", 1_234_500),
        )
    )


def itch_cancel_message() -> bytes:
    return b"".join(
        (
            b"X",
            struct.pack(">HH", 1, 3),
            (123_457).to_bytes(6, "big"),
            struct.pack(">Q", 0x0102_0304_0506_0708),
            struct.pack(">I", 25),
        )
    )


def mold_packet(sequence: int, messages: list[bytes]) -> bytes:
    body = b"".join(struct.pack(">H", len(message)) + message for message in messages)
    return b"TESTSESS01" + struct.pack(">QH", sequence, len(messages)) + body


def outputs() -> dict[Path, bytes]:
    itch = load("itch50.yaml")
    registers = load("registers.yaml")
    digest = schema_digest()
    add = mold_packet(1, [itch_add_message()])
    cancel = mold_packet(2, [itch_cancel_message()])
    heartbeat = mold_packet(3, [])
    malformed = add[:-3]
    vectors = {
        "schema_sha256": digest,
        "vectors": [
            {"file": "mold_add_order.bin", "sequence": 1, "messages": 1, "valid": True},
            {"file": "mold_cancel.bin", "sequence": 2, "messages": 1, "valid": True},
            {"file": "mold_heartbeat.bin", "sequence": 3, "messages": 0, "valid": True},
            {
                "file": "mold_truncated.bin",
                "sequence": 1,
                "messages": 1,
                "valid": False,
            },
        ],
    }
    return {
        ROOT / "protocol/generated/cpp/hft_protocol.hpp": cpp_header(
            itch, registers, digest
        ).encode(),
        ROOT / "protocol/generated/rust/protocol_generated.rs": rust_module(
            itch, registers, digest
        ).encode(),
        ROOT / "protocol/generated/vhdl/hft_protocol_pkg.vhd": vhdl_package(
            itch, registers, digest
        ).encode(),
        ROOT / "docs/generated/registers.md": register_markdown(
            registers, digest
        ).encode(),
        ROOT / "protocol/vectors/manifest.json": (
            json.dumps(vectors, indent=2, sort_keys=True) + "\n"
        ).encode(),
        ROOT / "protocol/vectors/mold_add_order.bin": add,
        ROOT / "protocol/vectors/mold_cancel.bin": cancel,
        ROOT / "protocol/vectors/mold_heartbeat.bin": heartbeat,
        ROOT / "protocol/vectors/mold_truncated.bin": malformed,
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check", action="store_true", help="fail if generated files are stale"
    )
    args = parser.parse_args()

    stale: list[str] = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_bytes() != content:
                stale.append(str(path.relative_to(ROOT)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)

    if stale:
        print("Generated files are stale:", file=sys.stderr)
        print("\n".join(f"  {path}" for path in stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
