set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(AARCH64_TRIPLE aarch64-linux-gnu CACHE STRING "AArch64 compiler triple")
set(CMAKE_C_COMPILER "${AARCH64_TRIPLE}-gcc")
set(CMAKE_CXX_COMPILER "${AARCH64_TRIPLE}-g++")

if(DEFINED ENV{AARCH64_SYSROOT})
  file(TO_CMAKE_PATH "$ENV{AARCH64_SYSROOT}" CMAKE_SYSROOT)
  set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
