[package]
name = "hft-rpmsg"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
hft-protocol = { path = "../protocol", version = "0.1.0" }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
mockall.workspace = true

[lints]
workspace = true
